### ISSUE TITLE
Tutorial or vignette 

### ISSUE THREAD

**Issue by mirkocelii** [anderssonlab/CAGEfightR_extensions#1]
Dear Robin,
many thanks for developing these CAGEfightR extension functions!
I was wondering if there is any tutorial or vignette available in order to apply these functions to CAGEfightR objects such as RSE or RES.

best,
Mirko

**Comment by anderssonrobin** [comment]
Dear Mirko,

Right now these functions are under development and primarily used in internal projects in the lab. We definitely aim to provide proper documentation to enable usage by others, but haven't had the time to do so yet. In the mean time, feel free to contact me if you have any specific questions on functions.

Best,
Robin

**Comment by mirkocelii** [comment]
Dear Robin,
Thanks for replying to me on Github!
I tried to write you an email  at andersson.robin@gmail.com but probably
you haven't seen it yet.
I'm a postdoc in Prof Valerio Orlando in Kaust, I just wanted to apply your
functions on a CAGEfightR object in order to have consistent approach with
Fantom for the eRNA call.
I was comparing some data created a few years ago by a previous student of
prof. Orlando [with his own code] according to your paper on Nature 2014,
and I find only 25-30% of overlap with CAGEfightR
I tried to look at the functions to understand which one I have to use, but
it's not very easy.
If you can just tell me which functions to use or the sequence of the
functions to be used it would be very helpful!

best,
Mirko
